name: Snapshot version & release
run-name: snapshot-version-release

on:
  issue_comment:
    types: [created]

jobs:
  snapshot-version-release:
    name: PR comment
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '!snapshot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Snapshot version
        id: snapshot-version
        run: npm run version:snapshot ${{ steps.extract-name.outputs.name }}

      - name: Snapshot release
        id: snapshot-release
        run: npm run release:snapshot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Post Comment with Result
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const author = context.payload.comment.user.login;
            const result = "hello"
            const body = `@${author} The snapshot version command ${result}.\n`;
            await github.rest.issues.createComment({ owner, repo, issue_number: number, body });