name: Prepare "Version Packages" PR
run-name: prepare-version-packages-pr

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
#    if: github.repository == 'clerkinc/javascript'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Create Release PR
        id: changesets
        uses: changesets/action@v1
        with:
          title: Version Packages
          commit: "chore(): Version packages"
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify on success
        if: steps.changesets.outputs.published == 'true'
        run: echo "Published!"