name: Test, lint and format
on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    concurrency:
      group: setup-${{ github.ref }}
      cancel-in-progress: true
    steps:
      #      - name: Checkout repo
      #        uses: actions/checkout@v3
      #      - name: Setup NodeJS
      #        uses: actions/setup-node@v3
      #        with:
      #          node-version: 18
      #      - run: npm ci
      #      - run: npm run build
      - run: touch nikos.txt && echo "test" > nikos.txt

  test:
    name: Tests
    needs: setup
    concurrency:
      group: test-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: ls -a

  Lint:
    name: Lint
    needs: setup
    concurrency:
      group: test-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: ls -a
